#!/bin/bash

rlwrap            \
	cat            \
	std/core.fs    \
	std/cond.fs    \
	std/comment.fs \
	std/manip.fs   \
	std/fmt.fs     \
	std/print.fs   \
	std/util.fs    \
	std/except.fs  \
	std/cstr.fs    \
	std/env.fs     \
	std/file.fs    \
	std/prelude.fs \
- | ./asforth