\ COND

: IF IMMEDIATE ' 0BRANCH , HERE @ 0 , ;

: THEN IMMEDIATE DUP HERE @ SWAP - SWAP ! ;

: ELSE IMMEDIATE 
	' BRANCH , HERE @
	0 , SWAP DUP
	HERE @ SWAP -
	SWAP ! ;

: UNLESS IMMEDIATE ' NOT , [COMPILE] IF ;

: BEGIN IMMEDIATE HERE @ ;

: UNTIL IMMEDIATE ' 0BRANCH , HERE @ - , ;

: AGAIN IMMEDIATE ' BRANCH , HERE @ - , ;

: WHILE IMMEDIATE ' 0BRANCH , HERE @ 0 , ;

: REPEAT IMMEDIATE 
	' BRANCH , SWAP HERE @ - ,
	DUP HERE @ SWAP - SWAP ! ;
